version: '3'
services:
  product-service:
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile.layered
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
