version: '3'
services:
  product-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: Dockerfile.layered
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
